kind: Service
apiVersion: v1
metadata:
  name: assignment
  namespace: assignment
spec:
  selector:
    app: assignment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
